### PR TITLE
[REPO] Add inventree-bulk-plugin

### PR DESCRIPTION
**Pull request by matmair**
@wolflu05 this PR would add inventree-bulk-plugin to the plugin list if that is ok for you.

### CODE REVIEW

**Comment by wolflu05** [comment]
Thanks for adding it. But I would like to wait a bit, until I addressed https://github.com/wolflu05/inventree-bulk-plugin/issues/19 and my already mentioned breaking change. Or should I just create a further pr then?

**Comment by matmair** [comment]
@wolflu05 no rush. We can wait till you think it is ready and modify the metadata to fit the changes.

I was just creating PRs for all public plugins that are fit for inclusion.

**Comment by wolflu05** [comment]
@matmair This would be ready now, would be good if you can update to the current readme. The project now is also on pypi.

**Comment by matmair** [comment]
@wolflu05 I will create a new Pr based on the pypi release - is a good test if all the automation still works

**Comment by matmair** [comment]
Superseded by #159

**Pull request closed without merging**
