### PR TITLE
Update inventree-bulk-plugin

### PR DESCRIPTION
**Pull request by wolflu05**
Since there is a new release now with an updated readme, I want to update the readme on the plugin list too. This also replaces the md images with html img tags inside of the details tags. Hopefully they work correctly this time.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
image

**Comment by wolflu05** [comment]
Interesting, I think im going to change the page to something more general like your wirewiz plugin and link to my documentation so that I don't need to resubmit it anytime I change something.

**Comment by matmair** [comment]
@wolflu05 so should I wait before I try to fix the errors?

**Comment by wolflu05** [comment]
Thank you for your offered help, but I removed the complete documentation and linked to my repo now after showing one example. I think that's a more convenient way to keep the provided documentation up to date. And additionally the netlify issues were fixed, maybe I removed the problematic code. This would be ready for merge now.

**Pull request merged**
