### PR TITLE
[REPO] Add inventree-cups-plugin

### PR DESCRIPTION
**Pull request by matmair**
@wolflu05 this would add your printer plugin to the new plugin repo if you are ok with it.
If you want you can also add a sentence or two about you (that will be rendered on your author page) and a website link in _publishers/wolflu05.md

### CODE REVIEW

**Comment by wolflu05** [comment]
Looks good. Although I have to look about when I have time adding something about me there. I think this can already be merged like this and I will create a separate pr?

**Comment by matmair** [comment]
@wolflu05 that is totally fine - there is no need to have anything there. You can always make a PR if there are changes you want to be made.

**Comment by matmair** [comment]
So should I move forward with the merge or should we wait?

**Comment by wolflu05** [comment]
Its fine, this can be merged from my side. I'll do a separate pr adding something about me some time.

**Pull request merged**
