### PR TITLE
Website copy editing

### PR DESCRIPTION
**Pull request by mechanarchy**
I fixed some typos, and made some wording changes that IMHO seem to read more smoothly.

Please feel free to comment if you object to any of these and I can improve/undo them.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Thanks @mechanarchy these changes all look good to me.

> Perhaps these would be better combined under the blog heading, since the majority of entries are there already.

Any major changes to site layout should be discussed over in https://github.com/inventree/inventree-website/pull/177

**Comment by matmair** [comment]
@mechanarchy the news section is used for creating a programmatic feed that is consumed by InvenTree instances and shown in the local interface, it is not targeted at human consumption.

**Comment by mechanarchy** [comment]
> @mechanarchy the news section is used for creating a programmatic feed that is consumed by InvenTree instances and shown in the local interface, it is not targeted at human consumption.

Respectfully @matmair, if it's not targeted for human consumption, then it probably shouldn't be linked in the website footer.

I see the distinction now, thank you. Perhaps it would be easier for instances to load the newsfeed if it's stored in a YAML or JSON manifest on the server? This is how I have seen some other projects choose to approach this problem.

It also readily lets news entries age out gracefully, have conditional display (such as for dev/beta/stable release channels), and any other metadata that may become useful in the future.

**Comment by SchrodingersGat** [comment]
@mechanarchy I'm on board with this approach, the "news" being visible on the site is confusing. It should be blog only, with a news entry created for each blog post also

**Comment by matmair** [comment]
@mechanarchy no offense taken. I am trying to explain why decisions were made and what will break if things are changed. I designed the whole website/repo/news thing without major inputs out of Greenfield, so there are less than-optimal things. RSS was selected because it is a well-known standard, making it interoperable and easy to use in future iterations of the main code base. Building something custom means that the person maintaining it only has a few resources to pull from when things fail.

If you want to contribute these theoretically possible things that would be great - feel free, I have no attachment or commitment to this code base.

**Pull request merged**
