### PR TITLE
Add translations to state section

### PR DESCRIPTION
**Pull request by matmair**
@SchrodingersGat for this to work you will need to set a secret named `CROWDIN_TOKEN`  with a token form `https://crowdin.com/settings#api-key` with at least `projects/projects` scope.

### CODE REVIEW

**Comment by matmair** [comment]
You would also need to allow the github bot to make changes to main

**Comment by SchrodingersGat** [comment]
@matmair the token has now been added - what do I need to look at to allow the github bot to change main?

**Comment by matmair** [comment]
@SchrodingersGat there should be setting for that in the protected branches.

**Comment by SchrodingersGat** [comment]
@matmair I'm having trouble locating that particular setting.. can you have a look?

**Comment by matmair** [comment]
@SchrodingersGat I added a PAT from a throw-away account, seems to work now

**Pull request merged**
