### PR TITLE
Added multi printer docu für Zebra label printer plugin

### PR DESCRIPTION
**Pull request by SergeoLacruz**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@SergeoLacruz interesting approach to address this limitation.

However I think this could be now solved using the *machines* interface - @wolflu05 any insight here?

**Comment by SergeoLacruz** [comment]
Not yet because of https://github.com/inventree/InvenTree/pull/6772

**Comment by SchrodingersGat** [comment]
@SergeoLacruz happy to merge?

**Review by matmair — APPROVED** [review]
LGTM

**Comment by SergeoLacruz** [comment]
Something has gone wrong. 
The build sysstem is unhappy with the link External link https://developer.digikey.com/ failed (status code 403).
The link is reachable but digikey sometimes throws mysterious errors on their developper pages. Shall I remove it?

**Comment by SchrodingersGat** [comment]
Don't remove the link - add an exception to the link checker.

**Pull request merged**
