### PR TITLE
Blog post about new features

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Closes https://github.com/inventree/inventree-website/issues/75

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matmair just headings so far - any that you think I've missed?

**Review by matmair — APPROVED** [review]
Looks good. We might add:
- refactored scheduling

**Comment by SchrodingersGat** [comment]
@matmair do you think this is "blog" or "news"?

**Comment by matmair** [comment]
@SchrodingersGat blog and then add a news item that links to the post

**Pull request merged**
