### PR TITLE
[REPO] Add plugin inventree-supplier-panel

### PR DESCRIPTION
**Pull request by SergeoLacruz**

### CODE REVIEW

**Comment by matmair** [comment]
@SergeoLacruz looks good in general. Just one nip-pick. It seems like your readme links to some images that are not integrated into this PR so the links are broken.
Great usage of the plugin system!

**Review by matmair — APPROVED** [review]

**Comment by SergeoLacruz** [comment]
Thaks fpr the hint. The pics are missing in the Zebra plugin description too.

**Comment by SergeoLacruz** [comment]
I copied the pics to assets and changed the links but the pictures still do not show up.

**Comment by matmair** [comment]
@SergeoLacruz the .png names files are not pngs but html files

**Comment by SergeoLacruz** [comment]
Ups...
Thanks for the hint. It is OK now

**Review by matmair — APPROVED** [review]
Nice

**Pull request merged**
